version: '3'

services:
  db:
    container_name: ms-user-db
    image: postgres:13.1
    ports:
      - ${TYPEORM_PORT}:5432
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}

  app:
    container_name: ms-user
    build: .
    ports:
      - ${PORT}:80
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    restart: on-failure
    environment:
      TYPEORM_HOST: db

volumes:
  node_modules:
